# Generated by Django 4.2.8 on 2023-12-20 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_manager', '0002_alter_labelmodel_name_alter_taskmodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
